[package]
name = "llmchat"
version = "0.1.0"
edition = "2024"


[features]
default = ["burn/dataset", "burn/sqlite-bundled", "dirs"]
f16 = []
dirs = ["dep:dirs"]

[dependencies]
burn = { version = "0.17", features = [
  "rocm",
  "vulkan",
  "dataset",
  "network",
  "train",
  "vision",
  "tch",
  "fusion",
  "wgpu",
  "experimental-named-tensor",
] }
tokio = { version = "1", features = ["full"] }

# Tokenizer
tokenizers = { version = "0.21.1", default-features = false, features = [
  "onig",
  "http",
] }

# Utils
derive-new = { version = "0.7.0" }
log = { version = "0.4.27" }
serde = { version = "1.0.219", features = ["std", "derive"] }
clap = { version = "4.5.37", features = ["derive"] }
rand = { version = "0.8.5", default-features = false, features = [
  "std_rng",
] } # std_rng is for no_std

dirs = { version = "6.0.0", optional = true }
axum = { version = "0.8.4", features = [
  "http2",
  "macros",
] }
axum-extra = {version = "0.10.1", features = ["typed-header"]}
tokio-stream = "0.1.17"
futures = "0.3.31"
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
headers = "0.4.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
async-trait = "0.1.88"